@url_dev = http://localhost:8888/v1/api

### signup
POST  {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "Shop Jake's",
    "email": "huuloc2026@gmail.com",
    "password": "abc123123123"
}