@url_dev = http://localhost:8888/v1/api

//
@randomName = USERNAME:++%2a%l5pbbz
@randomEmail = 711ezxc902zxc79ea4c.9284595f9@huuloc.com
@randomPassword = p:MWGh4R$x#fgyafhAj1
//

### signup
POST  {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "{{randomName}}",
    "email": "{{randomEmail}}",
    "password": "{{randomPassword}}"
}